# Linux Distro:
dist: xenial
# Programming language
language: python
# Python version to test
python: 
     - 3.5
     - 3.6
# Caching the pip dependencies
cache: pip
# Command to install dependencies
install: pip install -r requirements.txt
# Command to switch to test dir
before_install: cd Full\ Source\ Code\ of\ CDT\ \(1+1\)D/
# Command to run specific test.
script: python debugging.py
